language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="CXX=g++-4.9"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages:
        - g++-4.9
        - cmake
        - libssl-dev
before_install:
    - eval "${MATRIX_EVAL}"
install:
  - |
    pushd /tmp
    wget https://cmake.org/files/v3.12/cmake-3.12.0-rc2.tar.gz
    tar -xf cmake-3.12.0-rc2.tar.gz
    pushd cmake-3.12.0-rc2
    cmake . -DCMAKE_INSTALL_PREFIX=/tmp/cmake
    make install
    popd && popd
script:
  - /tmp/cmake/bin/cmake --version
  - mkdir build
  - cd build && /tmp/cmake/bin/cmake ..
  - make
  - ./test/unit_test